server:
  port: 9999

spring:
  application:
    name: fly-gateway

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: zuul网关-9999
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 2
    lease-expiration-duration-in-seconds: 5
zuul:
  routes:
    fly-cloud-consumer-admin:
      path: /api/admin/**
      serviceId: fly-cloud-consumer-admin
