server:
  port: 9100
  max-http-header-size: 10MB

spring:
  servlet:
    multipart:
      max-file-size : 10MB # 单个文件大小
      max-request-size: 100MB # 单次请求上传总文件大小

eureka:
  client:
    service-url:
      defaultZone: http://101.37.69.49:8761/eureka/
  instance:
    ip-address: 101.37.69.49
    hostname: ${eureka.instance.ip-address}
    instance-id: 文件服务消费方-9100
    prefer-ip-address: false
    lease-renewal-interval-in-seconds: 2
    lease-expiration-duration-in-seconds: 5

swagger:
  auth:
    server: http://101.37.69.49:8000/oauth/token

#feign:
#  httpclient:
#    enabled: true

# 全局参数设置
ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000
  SocketTimeout: 10000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 40000
            # (ribbonReadTimeout + ribbonConnectTimeout) * (maxAutoRetries + 1) * (maxAutoRetriesNextServer + 1);
            # (10000 +10000) * (0 + 1) * (1 + 1)