server:
  port: 8100
  max-http-header-size: 10MB

spring:
  servlet:
    multipart:
      max-file-size : 10MB # 单个文件大小
      max-request-size: 100MB # 单次请求上传总文件大小

eureka:
  client:
    service-url:
      defaultZone: http://${eureka.instance.ip-address}:8761/eureka/
  instance:
    ip-address: 127.0.0.1
    hostname: ${eureka.instance.ip-address}
    instance-id: 文件服务提供方-8100
    prefer-ip-address: false
    lease-renewal-interval-in-seconds: 2
    lease-expiration-duration-in-seconds: 5

fdfs:
  so-timeout: 1501  # 超时时间
  connect-timeout: 601 # 连接超时时间
  thumb-image: # 缩略图
    width: 60
    height: 60
  tracker-list: # tracker调度服务器 支持多个 默认22122
    - 101.37.69.49:22122
file:
  root-path: http://101.37.69.49/

swagger:
  auth:
    server: http://101.37.69.49:8000/oauth/token

# oauth2获取用户信息
security:
  oauth2:
    resource:
      id: current-user
      user-info-uri: http://101.37.69.49:9999/auth/user/current
      prefer-token-info: false