server:
  port: 9002
spring:
  application:
    name: cloud-admin-api
  zipkin:
    base-url: http://localhost:9411
  cloud:
    loadbalancer:
      retry:
        enabled: true
  boot:
    admin:
      client:
        url: http://localhost:9001
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: admin-api系统服务消费-8888
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 2
    lease-expiration-duration-in-seconds: 5
feign:
  hystrix:
    enabled: true

