spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: 'http://localhost:9999/auth/rsa/publicKey'
  redis:
    database: 0
    host: localhost
    port: 6379
    password:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 启用服务发现
          lower-case-service-id: true
      routes:
        - id: youlai-auth
            uri: lb://youlai-auth
            predicates:
              - Path=/auth/**
            filters:
              - StripPrefix=1
        - id: youlai-admin
          uri: lb://youlai-admin
          predicates:
            - Path=/admin/**
          filters:
            - StripPrefix=1

# 配置白名单路径
white:
    urls:
      - "/**/*.js"
      - "/**/*.css"
      - "/**/*.png"
      - "/auth/oauth/token"
      - "/auth/rsa/publicKey"