server:
  port: 8100
  max-http-header-size: 10MB

spring:
  servlet:
    multipart:
      max-file-size : 10MB # 单个文件大小
      max-request-size: 100MB # 单次请求上传总文件大小

eureka:
  client:
    serviceUrl:
      defaultZone: http://101.37.69.49:8761/eureka/
  instance:
    ip-address: 101.132.25.57
    hostname: ${eureka.instance.ip-address}
    instance-id: 文件服务提供方-8100
    prefer-ip-address: false
    lease-renewal-interval-in-seconds: 2
    lease-expiration-duration-in-seconds: 5

fdfs:
  so-timeout: 1501  # 超时时间
  connect-timeout: 601 # 连接超时时间
  thumb-image: # 缩略图
    width: 60
    height: 60
  tracker-list: # tracker调度服务器 支持多个 默认22122
    - 101.37.69.49:22122
file:
  root-path: http://101.37.69.49/

swagger:
  auth:
    server: http://101.37.69.49:8000/oauth/token

# oauth2获取用户信息
security:
  oauth2:
    resource:
      id: current-user
      user-info-uri: http://101.37.69.49:8000/user/current
      prefer-token-info: false

ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000
  SocketTimeout: 10000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 40000
            # (ribbonReadTimeout + ribbonConnectTimeout) * (maxAutoRetries + 1) * (maxAutoRetriesNextServer + 1);
            # (10000 +10000) * (0 + 1) * (1 + 1)