server:
  port: 9999
  max-http-header-size: 10MB

spring:
  servlet:
    multipart:
      max-file-size : 10MB # 单个文件大小
      max-request-size: 100MB # 单次请求上传总文件大小

zuul:
  routes:
    fly4j-auth:
      path: /auth/**
      sensitiveHeaders:
      serviceId: fly4j-auth
      stripPrefix: true # path前缀是否删除
    fly4j-system:
      path: /system/**
      sensitiveHeaders:
      serviceId: fly4j-system
      stripPrefix: true # path前缀是否删除
    fly4j-file:
      path: /files/**
      sensitiveHeaders:
      serviceId: fly4j-file
      stripPrefix: false # 不会删除files
    shop-goods:
      path: /goods/**
      sensitiveHeaders:
      serviceId: shop-goods
      stripPrefix: true
    shop-order:
      path: /orders/**
      sensitiveHeaders:
      serviceId: shop-order
      stripPrefix: false  # 不删除 orders
    shop-marketing:
      path: /marketing/**
      sensitiveHeaders:
      serviceId: shop-marketing
      stripPrefix: true
  host:
    connectTimeoutMillis: 5000

eureka:
  client:
    service-url:
      defaultZone: http://101.37.69.49:8761/eureka/
  instance:
    ip-address: localhost
    hostname: ${eureka.instance.ip-address}
    instance-id: 网关-9999
    prefer-ip-address: false
    lease-renewal-interval-in-seconds: 2
    lease-expiration-duration-in-seconds: 5


# 全局参数设置
ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000
  SocketTimeout: 10000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 40000
            # (ribbonReadTimeout + ribbonConnectTimeout) * (maxAutoRetries + 1) * (maxAutoRetriesNextServer + 1);
            # (10000 +10000) * (0 + 1) * (1 + 1)