server:
  port: 8004

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://101.37.69.49:3306/yshop-sms?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&autoReconnect=true
    username: root
    password: 123456

mybatis-plus:
  configuration:
    # 驼峰下划线转换
    map-underscore-to-camel-case: false
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

eureka:
  client:
    service-url:
      defaultZone: http://101.37.69.49:8761/eureka/
  instance:
    ip-address: localhost
    hostname: ${eureka.instance.ip-address}
    instance-id:  SMS营销服务-8004
    prefer-ip-address: false
    lease-renewal-interval-in-seconds: 2
    lease-expiration-duration-in-seconds: 5

# oauth2获取用户信息
security:
  oauth2:
    resource:
      id: current-user
      user-info-uri: http://101.132.25.57:9999/auth/user/current
      prefer-token-info: false

# swagger 认证配置
swagger:
  auth:
    server: http://101.37.69.49:8000/oauth/token

ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000
  SocketTimeout: 10000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 40000
            # (ribbonReadTimeout + ribbonConnectTimeout) * (maxAutoRetries + 1) * (maxAutoRetriesNextServer + 1);
            # (10000 +10000) * (0 + 1) * (1 + 1)