server:
  port: 8888

spring:
  application:
    name: fly-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/fly2021/fly-cloud.git
          search-paths: fly-config-properties
    bus:
      refresh:
        enabled: true
  kafka:
    bootstrap-servers: 101.37.69.49:9092
    consumer:
      group-id: config-server

eureka:
  instance:
    instance-id: 配置中心-8888
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 20
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    registry-fetch-interval-seconds: 10

# 暴露刷新url：/actuator/bus-refresh
management:
  endpoints:
    web:
      exposure:
        include: '*'