server:
  port: 7003
spring:
  application:
    name: fly-eureka-server
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZonne: http://${eureka.instance.hostname}:${server.port}/eureka/
  instance:
    hostname: fly-eureka
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 5000