server:
  port: 9001
spring:
  application:
    name: fly-cloud-consumer-admin
  cloud:
    loadbalancer:
      retry:
        enabled: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
  instance:
    instance-id: 系統消费方服务-9001
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 2
    lease-expiration-duration-in-seconds: 5
feign:
  hystrix:
    enabled: true

