server:
  port: 8888

spring:
  application:
    name:  fly-config
  zipkin:
    base-url: http://localhost:9411
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config/
  boot:
    admin:
      client:
        url: http://localhost:9001
eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 20
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    registry-fetch-interval-seconds: 10
